### ISSUE TITLE
Can't Update MINTS Description

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2564]
I'm running the latest and getting this when I try to compose an issuance to update the description.

```
{
"error": "['cannot issue during fair minting']"
}
```

**Comment by adamkrellenstein** [comment]
This seems like a DB consistency issue. I would recommend a from-scratch reparse or the use of the latest bootstrap.

**Comment by droplister** [comment]
I still get this error after a full reparse.

```
Counterparty Core v10.5.0
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /home/rsa-key-20240114/.config/counterparty/server.conf
Counterparty Database: /home/rsa-key-20240114/.local/share/counterparty/counterparty.db
Counterparty API Database: /home/rsa-key-20240114/.local/share/counterparty/counterparty.api.db
Rust Fetcher Database: /home/rsa-key-20240114/.local/share/counterparty/fetcherdb
Server Log: /home/rsa-key-20240114/.cache/counterparty/log/server.log
API Access Log: /home/rsa-key-20240114/.cache/counterparty/log/server.access.log

------------------------------ REPARSE ------------------------------

[OK] Rolling database back to Block 0... (in 1264.80s)
[OK] Recalculating consensus hashes... (in 24.76s)
[OK] Block 867036 parsed in 0.02s [588767/588767 blocks parsed - 4:24:53/4:24:53 (0:00:00)] (in 15893.65s)
...
Oct 24 00:41:19 counterparty-core-1 counterparty-server[2470812]: 2024-10-24T00:41:19.446+00:00 - [    INFO] - Stopping prefetcher...
Oct 24 00:41:28 counterparty-core-1 counterparty-server[2470812]: 2024-10-24T00:41:28.122+00:00 - [    INFO] - Catch up complete.
Oct 24 00:41:28 counterparty-core-1 counterparty-server[2470812]: 2024-10-24T00:41:28.133+00:00 - [    INFO] - Watching for new blocks...
```

**Comment by droplister** [comment]
This still doesn't work with 10.6
http://35.209.11.245:4000/v2/addresses/1FairPYzS6MJJq5fPQqf3M58ZxJEpkiGfX/compose/issuance?asset=MINTS&quantity=0&description=https://www.xcp.io/json/mints.json

**Comment by ouziel-slama** [comment]
`fair_minting` is False in the last issuance https://dev.counterparty.io:4000/v2/assets/MINTS/issuances?limit=1
and fairminter is closed https://dev.counterparty.io:4000/v2/assets/MINTS/fairminters
indeed that should works!

**Comment by ouziel-slama** [comment]
@droplister this is very weird.. you should not get this error because `fair_minting==False` here http://35.209.11.245:4000/v2/assets/MINTS/issuances?limit=1.
And the query works fine on all other servers.
Can you please try to put a `print(last_issuance)` here https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/messages/issuance.py#L257 and share the logs when you try the query ? thanks.

**Comment by ouziel-slama** [comment]
OK managed to reproduce and fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2679

**Comment by droplister** [comment]
Amazing, sorry I wasnt able to produce the log you requested.

**Comment by droplister** [comment]
I got the error still from compose on 10.7 but i got around it with validate=false, will see if it confirms properly.
